name: 'Build Android APK com EAS'

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4.1.7

      - name: Configurar Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'

      - name: Instalar dependências
        run: yarn install

      - name: Instalar EAS CLI
        run: yarn global add eas-cli

      - name: Fazer login no EAS (Expo)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas whoami || eas login --token $EXPO_TOKEN

      - name: Gerar APK de produção
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile production --non-interactive | tee build.log

      - name: Extrair link do APK do log
        run: |
          grep -o 'https://expo.dev/artifacts[^ ]*\.apk' build.log > apk-url.txt

      - name: Fazer upload do link do APK como artefato
        uses: actions/upload-artifact@v4.3.6
        with:
          name: apk-url
          path: apk-url.txt