name: 'Build Android APK with EAS'

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Login no EAS (Expo)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas whoami || eas login --token $EXPO_TOKEN

      - name: Build APK de produção
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile production --non-interactive | tee build.log

      - name: Extrair link do APK do log
        run: |
          grep -o 'https://expo.dev/artifacts[^ ]*\.apk' build.log > apk-url.txt

      - name: Upload APK URL como artefato
        uses: actions/upload-artifact@v4.3.6
        with:
          name: apk-url
          path: apk-url.txt